import os
import numpy as np
import gensim
import gensim.downloader


UNI_UID2UNAME = {0: 'backpack', 1: 'umbrella', 2: 'bag', 3: 'tie', 4: 'suitcase', 5: 'case', 6: 'bird',
                 7: 'cat', 8: 'dog', 9: 'horse', 10: 'sheep', 11: 'cow', 12: 'elephant', 13: 'bear',
                 14: 'zebra', 15: 'giraffe', 16: 'animal_other', 17: 'microwave', 18: 'radiator', 19: 'oven',
                 20: 'toaster', 21: 'storage_tank', 22: 'conveyor_belt', 23: 'sink', 24: 'refrigerator',
                 25: 'washer_dryer', 26: 'fan', 27: 'dishwasher', 28: 'toilet', 29: 'bathtub', 30: 'shower',
                 31: 'tunnel', 32: 'bridge', 33: 'pier_wharf', 34: 'tent', 35: 'building', 36: 'ceiling',
                 37: 'laptop', 38: 'keyboard', 39: 'mouse', 40: 'remote', 41: 'cell phone', 42: 'television',
                 43: 'floor', 44: 'stage', 45: 'banana', 46: 'apple', 47: 'sandwich', 48: 'orange',
                 49: 'broccoli', 50: 'carrot', 51: 'hot_dog', 52: 'pizza', 53: 'donut', 54: 'cake',
                 55: 'fruit_other', 56: 'food_other', 57: 'chair_other', 58: 'armchair', 59: 'swivel_chair',
                 60: 'stool', 61: 'seat', 62: 'couch', 63: 'trash_can', 64: 'potted_plant', 65: 'nightstand',
                 66: 'bed', 67: 'table', 68: 'pool_table', 69: 'barrel', 70: 'desk', 71: 'ottoman',
                 72: 'wardrobe', 73: 'crib', 74: 'basket', 75: 'chest_of_drawers', 76: 'bookshelf',
                 77: 'counter_other', 78: 'bathroom_counter', 79: 'kitchen_island', 80: 'door', 81: 'light_other',
                 82: 'lamp', 83: 'sconce', 84: 'chandelier', 85: 'mirror', 86: 'whiteboard', 87: 'shelf',
                 88: 'stairs', 89: 'escalator', 90: 'cabinet', 91: 'fireplace', 92: 'stove', 93: 'arcade_machine',
                 94: 'gravel', 95: 'platform', 96: 'playingfield', 97: 'railroad', 98: 'road', 99: 'snow',
                 100: 'sidewalk_pavement', 101: 'runway', 102: 'terrain', 103: 'book', 104: 'box', 105: 'clock',
                 106: 'vase', 107: 'scissors', 108: 'plaything_other', 109: 'teddy_bear', 110: 'hair_dryer',
                 111: 'toothbrush', 112: 'painting', 113: 'poster', 114: 'bulletin_board', 115: 'bottle', 116: 'cup',
                 117: 'wine_glass', 118: 'knife', 119: 'fork', 120: 'spoon', 121: 'bowl', 122: 'tray', 123: 'range_hood',
                 124: 'plate', 125: 'person', 126: 'rider_other', 127: 'bicyclist', 128: 'motorcyclist', 129: 'paper',
                 130: 'streetlight', 131: 'road_barrier', 132: 'mailbox', 133: 'cctv_camera', 134: 'junction_box',
                 135: 'traffic_sign', 136: 'traffic_light', 137: 'fire_hydrant', 138: 'parking_meter', 139: 'bench',
                 140: 'bike_rack', 141: 'billboard', 142: 'sky', 143: 'pole', 144: 'fence', 145: 'railing_banister',
                 146: 'guard_rail', 147: 'mountain_hill', 148: 'rock', 149: 'frisbee', 150: 'skis', 151: 'snowboard',
                 152: 'sports_ball', 153: 'kite', 154: 'baseball_bat', 155: 'baseball_glove', 156: 'skateboard',
                 157: 'surfboard', 158: 'tennis_racket', 159: 'net', 160: 'base', 161: 'sculpture', 162: 'column',
                 163: 'fountain', 164: 'awning', 165: 'apparel', 166: 'banner', 167: 'flag', 168: 'blanket',
                 169: 'curtain_other', 170: 'shower_curtain', 171: 'pillow', 172: 'towel', 173: 'rug_floormat',
                 174: 'vegetation', 175: 'bicycle', 176: 'car', 177: 'autorickshaw', 178: 'motorcycle', 179: 'airplane',
                 180: 'bus', 181: 'train', 182: 'truck', 183: 'trailer', 184: 'boat_ship', 185: 'slow_wheeled_object',
                 186: 'river_lake', 187: 'sea', 188: 'water_other', 189: 'swimming_pool', 190: 'waterfall',
                 191: 'wall', 192: 'window', 193: 'window_blind', 255: 'unlabeled'}

UNAME2EM_NAME = {'backpack': 'backpack', 'umbrella': 'umbrella', 'bag': 'bag', 'tie': 'tie',
                 'suitcase': 'suitcase', 'case': 'case', 'bird': 'bird', 'cat': 'cat', 'dog': 'dog',
                 'horse': 'horse', 'sheep': 'sheep', 'cow': 'cow', 'elephant': 'elephant', 'bear': 'bear',
                 'zebra': 'zebra', 'giraffe': 'giraffe', 'animal_other': 'animal',
                 'microwave': 'microwave', 'radiator': 'radiator', 'oven': 'oven', 'toaster': 'toaster',
                 'storage_tank': 'storage_tank', 'conveyor_belt': 'conveyor belt', 'sink': 'sink',
                 'refrigerator': 'refrigerator', 'washer_dryer': 'washer dryer', 'fan': 'fan',
                 'dishwasher': 'dishwasher', 'toilet': 'toilet', 'bathtub': 'bathtub', 'shower': 'shower',
                 'tunnel': 'tunnel', 'bridge': 'bridge', 'pier_wharf': 'pier wharf', 'tent': 'tent',
                 'building': 'building', 'ceiling': 'ceiling', 'laptop': 'laptop', 'keyboard': 'keyboard',
                 'mouse': 'mouse', 'remote': 'remote', 'cell phone': 'cell phone', 'television': 'television',
                 'floor': 'floor', 'stage': 'stage', 'banana': 'banana', 'apple': 'apple', 'sandwich': 'sandwich',
                 'orange': 'orange', 'broccoli': 'broccoli', 'carrot': 'carrot', 'hot_dog': 'hotdog',
                 'pizza': 'pizza', 'donut': 'donut', 'cake': 'cake', 'fruit_other': 'fruit',
                 'food_other': 'food', 'chair_other': 'chair', 'armchair': 'arm chair',
                 'swivel_chair': 'swivel chair', 'stool': 'stool', 'seat': 'seat', 'couch': 'couch',
                 'trash_can': 'trash can', 'potted_plant': 'potted plant', 'nightstand': 'nightstand',
                 'bed': 'bed', 'table': 'table', 'pool_table': 'pool table', 'barrel': 'barrel', 'desk': 'desk',
                 'ottoman': 'ottoman', 'wardrobe': 'wardrobe', 'crib': 'crib', 'basket': 'basket',
                 'chest_of_drawers': 'chest of drawers', 'bookshelf': 'bookshelf', 'counter_other': 'counter',
                 'bathroom_counter': 'bathroom counter', 'kitchen_island': 'kitchen island', 'door': 'door',
                 'light_other': 'light', 'lamp': 'lamp', 'sconce': 'sconce', 'chandelier': 'chandelier',
                 'mirror': 'mirror', 'whiteboard': 'whiteboard', 'shelf': 'shelf', 'stairs': 'stairs',
                 'escalator': 'escalator', 'cabinet': 'cabinet', 'fireplace': 'fireplace', 'stove': 'stove',
                 'arcade_machine': 'arcade machine', 'gravel': 'gravel', 'platform': 'platform',
                 'playingfield': 'playing field', 'railroad': 'railroad', 'road': 'road', 'snow': 'snow',
                 'sidewalk_pavement': 'sidewalk pavement', 'runway': 'runway', 'terrain': 'terrain',
                 'book': 'book', 'box': 'box', 'clock': 'clock', 'vase': 'vase', 'scissors': 'scissors',
                 'plaything_other': 'plaything other', 'teddy_bear': 'teddy bear', 'hair_dryer': 'hair dryer',
                 'toothbrush': 'toothbrush', 'painting': 'painting', 'poster': 'poster', 'bulletin_board': 'bulletin board',
                 'bottle': 'bottle', 'cup': 'cup', 'wine_glass': 'wine glass', 'knife': 'knife', 'fork': 'fork',
                 'spoon': 'spoon', 'bowl': 'bowl', 'tray': 'tray', 'range_hood': 'range hood', 'plate': 'plate',
                 'person': 'person', 'rider_other': 'rider', 'bicyclist': 'bicyclist', 'motorcyclist': 'motorcyclist',
                 'paper': 'paper', 'streetlight': 'streetlight', 'road_barrier': 'road barrier', 'mailbox': 'mailbox',
                 'cctv_camera': 'cctv camera', 'junction_box': 'junction box', 'traffic_sign': 'traffic sign',
                 'traffic_light': 'traffic light', 'fire_hydrant': 'fire hydrant', 'parking_meter': 'parking meter',
                 'bench': 'bench', 'bike_rack': 'bike rack', 'billboard': 'billboard', 'sky': 'sky', 'pole': 'pole',
                 'fence': 'fence', 'railing_banister': 'railing banister', 'guard_rail': 'guard rail',
                 'mountain_hill': 'mountain hill', 'rock': 'rock', 'frisbee': 'frisbee', 'skis': 'skis', 'snowboard': 'snowboard',
                 'sports_ball': 'sports ball', 'kite': 'kite', 'baseball_bat': 'baseball bat', 'baseball_glove': 'baseball glove',
                 'skateboard': 'skateboard', 'surfboard': 'surfboard', 'tennis_racket': 'tennis_racket', 'net': 'net',
                 'base': 'base', 'sculpture': 'sculpture', 'column': 'column', 'fountain': 'fountain', 'awning': 'awning',
                 'apparel': 'apparel', 'banner': 'banner', 'flag': 'flag', 'blanket': 'blanket', 'curtain_other': 'other curtain',
                 'shower_curtain': 'shower curtain', 'pillow': 'pillow', 'towel': 'towel', 'rug_floormat': 'rug floormat',
                 'vegetation': 'vegetation', 'bicycle': 'bicycle', 'car': 'car', 'autorickshaw': 'autorickshaw',
                 'motorcycle': 'motorcycle', 'airplane': 'airplane', 'bus': 'bus', 'train': 'train', 'truck': 'truck',
                 'trailer': 'trailer', 'boat_ship': 'boat ship', 'slow_wheeled_object': 'slow wheeled object',
                 'river_lake': 'river lake', 'sea': 'sea', 'water_other': 'water', 'swimming_pool': 'swimming pool',
                 'waterfall': 'waterfall', 'wall': 'wall', 'window': 'window', 'window_blind': 'window blind',
                 'unlabeled': 'unlabeled'}


ALL_LABEL2ID = {'backpack': 0, 'umbrella': 1, 'bag': 2, 'tie': 3, 'suitcase': 4, 'case': 5, 'bird': 6, 'cat': 7,
                'dog': 8, 'horse': 9, 'sheep': 10, 'cow': 11, 'elephant': 12, 'bear': 13, 'zebra': 14,
                'giraffe': 15, 'animal_other': 16, 'microwave': 17, 'radiator': 18, 'oven': 19, 'toaster': 20,
                'storage_tank': 21, 'conveyor_belt': 22, 'sink': 23, 'refrigerator': 24, 'washer_dryer': 25,
                'fan': 26, 'dishwasher': 27, 'toilet': 28, 'bathtub': 29, 'shower': 30, 'tunnel': 31,
                'bridge': 32, 'pier_wharf': 33, 'tent': 34, 'building': 35, 'ceiling': 36, 'laptop': 37,
                'keyboard': 38, 'mouse': 39, 'remote': 40, 'cell phone': 41, 'television': 42, 'floor': 43,
                'stage': 44, 'banana': 45, 'apple': 46, 'sandwich': 47, 'orange': 48, 'broccoli': 49,
                'carrot': 50, 'hot_dog': 51, 'pizza': 52, 'donut': 53, 'cake': 54, 'fruit_other': 55,
                'food_other': 56, 'chair_other': 57, 'armchair': 58, 'swivel_chair': 59, 'stool': 60,
                'seat': 61, 'couch': 62, 'trash_can': 63, 'potted_plant': 64, 'nightstand': 65, 'bed': 66,
                'table': 67, 'pool_table': 68, 'barrel': 69, 'desk': 70, 'ottoman': 71, 'wardrobe': 72,
                'crib': 73, 'basket': 74, 'chest_of_drawers': 75, 'bookshelf': 76, 'counter_other': 77,
                'bathroom_counter': 78, 'kitchen_island': 79, 'door': 80, 'light_other': 81, 'lamp': 82,
                'sconce': 83, 'chandelier': 84, 'mirror': 85, 'whiteboard': 86, 'shelf': 87, 'stairs': 88,
                'escalator': 89, 'cabinet': 90, 'fireplace': 91, 'stove': 92, 'arcade_machine': 93, 'gravel': 94,
                'platform': 95, 'playingfield': 96, 'railroad': 97, 'road': 98, 'snow': 99,
                'sidewalk_pavement': 100, 'runway': 101, 'terrain': 102, 'book': 103, 'box': 104, 'clock': 105,
                'vase': 106, 'scissors': 107, 'plaything_other': 108, 'teddy_bear': 109, 'hair_dryer': 110,
                'toothbrush': 111, 'painting': 112, 'poster': 113, 'bulletin_board': 114, 'bottle': 115,
                'cup': 116, 'wine_glass': 117, 'knife': 118, 'fork': 119, 'spoon': 120, 'bowl': 121, 'tray': 122,
                'range_hood': 123, 'plate': 124, 'person': 125, 'rider_other': 126, 'bicyclist': 127,
                'motorcyclist': 128, 'paper': 129, 'streetlight': 130, 'road_barrier': 131, 'mailbox': 132,
                'cctv_camera': 133, 'junction_box': 134, 'traffic_sign': 135, 'traffic_light': 136,
                'fire_hydrant': 137, 'parking_meter': 138, 'bench': 139, 'bike_rack': 140, 'billboard': 141,
                'sky': 142, 'pole': 143, 'fence': 144, 'railing_banister': 145, 'guard_rail': 146,
                'mountain_hill': 147, 'rock': 148, 'frisbee': 149, 'skis': 150, 'snowboard': 151,
                'sports_ball': 152, 'kite': 153, 'baseball_bat': 154, 'baseball_glove': 155, 'skateboard': 156,
                'surfboard': 157, 'tennis_racket': 158, 'net': 159, 'base': 160, 'sculpture': 161, 'column': 162,
                'fountain': 163, 'awning': 164, 'apparel': 165, 'banner': 166, 'flag': 167, 'blanket': 168,
                'curtain_other': 169, 'shower_curtain': 170, 'pillow': 171, 'towel': 172, 'rug_floormat': 173,
                'vegetation': 174, 'bicycle': 175, 'car': 176, 'autorickshaw': 177, 'motorcycle': 178,
                'airplane': 179, 'bus': 180, 'train': 181, 'truck': 182, 'trailer': 183, 'boat_ship': 184,
                'slow_wheeled_object': 185, 'river_lake': 186, 'sea': 187, 'water_other': 188, 'swimming_pool': 189,
                'waterfall': 190, 'wall': 191, 'window': 192, 'window_blind': 193, 'chopsticks': 194,
                'musical instrument': 195, 'drink': 196, 'wrench': 197, 'mule(which is a type of animal)': 198,
                'camel(which is a type of animal)': 199, 'tap': 200, 'snowmobile': 201, 'fish': 202,
                'crocodile(which is a type of animal)': 203, 'screwdriver': 204,
                'panda(which is a type of animal)': 205, 'pig(which is a type of animal)': 206,
                'red panda(which is a type of animal)': 207, 'frying pan': 208,
                'monkey(which is a type of animal)': 209, 'kangaroo(which is a type of animal)': 210,
                'leopard(which is a type of animal)': 211, 'koala(which is a type of animal)': 212,
                'lion(which is a type of animal)': 213, 'hammer': 214, 'tiger(which is a type of animal)': 215,
                'camera': 216, 'starfish': 217, 'drill': 218, 'rhinoceros(which is a type of animal)': 219,
                'hippopotamus(which is a type of animal)': 220, 'turtle': 221, 'flashlight': 222,
                'rabbit(which is a type of animal)': 223, 'skull': 224, 'kettle': 225, 'fox': 226,
                'lynx(which is a type of animal)': 227, 'hat': 228, 'harbor seal': 229,
                'alpaca(which is a type of animal)': 230, 'teapot': 231, 'glove': 232,
                'sea lion(which is a type of animal)': 233, 'printer': 234, 'balloon': 235, 'stapler': 236,
                'calculator': 237, 'unlabeled': 255}
